name: CI/CD BACKEND BCR

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # DB_HOST: ${{ secrets.DB_HOST }}
      # DB_PORT: ${{ secrets.DB_PORT }}
      # DB_DATABASE: ${{ secrets.DB_DATABASE }}
      # DB_USER: ${{ secrets.DB_USER }}
      # DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Run Build
        run: |
          npm ci --include=dev
      - name: Run linter
        run: npm run eslint
      - name: Run tests
        run: |
          echo "Running Test On CI/CD",
          npm run test
